### ISSUE TITLE
PHP 8.1 support?

### ISSUE THREAD

**Issue by mergims** [pantheon-systems/docker-build-tools-ci#102]
No image available that supports PHP 8.1 yet. Any plans on this?

**Comment by greg-1-anderson** [comment]
We do not recommend PHP 8.1 on Pantheon yet due to a bug in mysqlproxy. A fix is in the works. Once PHP 8.1 is supported on the platform, we will provide an 8.1 image here as well.

**Comment by mergims** [comment]
@greg-1-anderson is there still a bug with mysqlproxy?

**Comment by wilburec** [comment]
Also wondering why this is so out of date.  Thanks!

**Comment by brooke-heaton** [comment]
Any updates on this? Our build process is currently stuck.

**Comment by greg-1-anderson** [comment]
PHP 8.1 is now supported on Pantheon. We don't have a specific ETA for creating a Build Tools image.

**Comment by greg-1-anderson** [comment]
Tracking internally as FEAT-696

**Comment by kporras07** [comment]
New image tag is ready: 8.x-php8.1
