### ISSUE TITLE
Keep installed items up to date

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/docker-build-tools-ci#17]
In order to keep the installed binaries, such as Terminus, Terminus plugins, and Headless Chrome, up to date the Dockerfile needs to periodically be rebuild.

I suggest we use [a scheduled CircleCI job](https://circleci.com/docs/2.0/triggers/#scheduled-builds) to trigger builds [via the quay.io API](https://docs.quay.io/api/).

**Comment by ataylorme** [comment]
@greg-1-anderson I would love your thoughts on how we would tag images with this approach. For example, build tools is moving to the `4.x` tag.

If that tag were to rebuild daily, there is a chance the updated binaries could break things.

Perhaps we could have a `4.x-nightly` tag that is automatically built, set up some more thorough testing, either manual or automated, to ensure compatibility, then update the `4.x` tag if testing goes well

**Comment by greg-1-anderson** [comment]
I prefer manual updates here. I don't think there is a large need for CI tasks to use the most recent version of the tools. On the flip side, there is a need for CI tasks to be stable for as long as possible.

I think that in situations when we know there is a strong need to update the container, e.g. for a bugfix, we can manually rebuild. We bump the major version (e.g. to 4.x) when making an incompatible change. Overalll I think this process is working fine.

**Comment by ataylorme** [comment]
Okay, aside from build tools updates, I would like to re-run the build periodically to get the latest Chrome, even when there is no build tools activity.

**Comment by greg-1-anderson** [comment]
Hm, wish there was a better way to use headless chrome from a separate docker image. I don't want to have to re-run the build here just to get a newer chrome.

**Comment by ataylorme** [comment]
We could start from the Behat Chrome Driver `Dockerfile` at [`DMore/docker-chrome-headless`](https://gitlab.com/DMore/docker-chrome-headless/blob/7.2/Dockerfile) but then we wouldn't have Drush, Composer and some of the other things from `drupaldocker/php:7.2-cli` so would need to install those manually.

That seems more like a lateral move than an improvement

**Comment by greg-1-anderson** [comment]
I meant running headless chrome in a separate server, the same way that you set up a mysql server for Drupal testing on Circle.

**Comment by ataylorme** [comment]
That would be fine too but we would still need to maintain a `Dockerfile` with headless Chrome and Terminus in it.

Even if we split out the Behat preparation to its own job and had a job that only ran Behat we would still need Terminus since we are using `terminus wp` as the binary for the WordHat `wp-cli` driver.
