### ISSUE TITLE
CircleCI Base Image

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/docker-build-tools-ci#26]
[CircleCI maintains many Docker images](https://hub.docker.com/u/circleci), including Node and PHP, both with variants having browsers installed. They also take care of creating an unprivileged user.

I think using `circleci/php:7-node-browsers` as a base could be beneficial, rather than installing Headless Chrome (required for Behat) ourselves.

Having Node available could also consolidate so we can use the same image for JavaScript-based tests, such as Backstop visual regression

**Comment by ataylorme** [comment]
Per meeting with @greg-1-anderson and @stevector this sounds like a good idea. I'll explore moving forward after I return from WCEU

**Comment by mrdavidburns** [comment]
+1 for having node included. Just spent a decent amount of time getting it installed with `docker-build-tools-ci` so that I could compile Sass.

**Comment by ataylorme** [comment]
@mrdavidburns have you tried using a Node image for a stand-alone job to compile Sass then persisting the output to a deploy job? The benefit to that approach is you can run the Composer build and Node build in parallel, then take the artifacts from both and run a deploy job. This will be quite a bit faster than one monolithic job building Composer and Node artifacts in sequence.

[Here is an example](https://github.com/ataylorme/ataylorme-wordpress/blob/0d98f783b3ec6901ac18005603cadba95e6bcec4/.circleci/config.yml#L93:L121)

**Comment by ataylorme** [comment]
@mrdavidburns I have a PR open for this (#27). You can test the CircleCI PHP + Node + Browser image by using `quay.io/pantheon-public/build-tools-ci:from-circleci-php`. I've successfully run `gulp`, `lighthouse`, and other Node tasks with it.

Having you try it for a second +1 would be great.
