### ISSUE TITLE
Don't re-install Build Tools

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/docker-build-tools-ci#33]
The `6.x` tag currently [re-installs Build Tools in a different version if requested](https://github.com/pantheon-systems/docker-build-tools-ci/blob/6.x/scripts/set-environment#L132:L137)

We should just stick with the latest tagged version in this Dockefile.

> I think that only the Terminus Build Tools plugin project itself needs that.

**Comment by kporras07** [comment]
A warning message was added to prevent people do the reinstall but I think that's something we should keep supporting for complex use cases (e.g. current circleci-orb) or even getting an updated version of the plugin when a new image has not been released.

I'm closing this, feel free to reopen/create new issue if further discussion is needed
