### ISSUE TITLE
Consider making Docker image available on Github's Docker registry

### ISSUE THREAD

**Issue by davereid** [pantheon-systems/docker-build-tools-ci#58]
quay.io has had [significant downtime in the last two weeks](https://status.quay.io/history), which affects our ability to push code to Pantheon for Drupal 8 projects with CircleCI, which is a critical task. I would ask to consider making this project's Docker images available using Github's Docker registry: https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages

**Comment by greg-1-anderson** [comment]
Yeah I have been considering this. Quay's extended downtime incidents have been a serious impediment lately.

**Comment by davereid** [comment]
Yeah, at least if Github is down for some reason, we're not going to be pushing code at all anyway.

**Comment by dnackers** [comment]
We're experiencing the same pain points @davereid outlines above.  We rely heavily on the Drupal8 + CircleCI workflow and have been forced to develop workarounds the past couple weeks.

**Comment by jpkarvonen** [comment]
Any progress on this? Quay is down at the time of posting this comment, so this issue is top of mind.

**Comment by kporras07** [comment]
We recently pushed this image to DockerHub as an alternate registry: https://hub.docker.com/repository/docker/pantheonpublic/build-tools-ci
