### ISSUE TITLE
Expose environment security lock user/pass for automated tests

### ISSUE THREAD

**Issue by jameswilson** [pantheon-systems/docker-build-tools-ci#59]
Visual regression tests fail when comparing against a locked Dev environment because the `DEV_SITE_URL` environment variable does not include the HTTP Basic Authentication username and password.

This line is where visual regression tests need the correct URL

https://github.com/pantheon-systems/example-drops-8-composer/blob/master/.ci/test/visual-regression/backstopConfig.js#L2

This line is where the variable is set:

https://github.com/pantheon-systems/docker-build-tools-ci/blob/6.x/scripts/set-environment#L90

There is a way to get the username and password for all the relevant environments using the following terminus commands:

```
MULTIDEV_SITE_USER=$(terminus lock:info $TERMINUS_SITE.$TERMINUS_ENV --field=username)
MULTIDEV_SITE_PASSWORD=$(terminus lock:info $TERMINUS_SITE.$TERMINUS_ENV --field=password)
DEV_SITE_USER=$(terminus lock:info $TERMINUS_SITE.dev --field=username)
DEV_SITE_PASSWORD=$(terminus lock:info $TERMINUS_SITE.dev --field=password)
TEST_SITE_USER=$(terminus lock:info $TERMINUS_SITE.test --field=username)
TEST_SITE_PASSWORD=$(terminus lock:info $TERMINUS_SITE.test --field=password)
LIVE_SITE_USER=$(terminus lock:info $TERMINUS_SITE.live --field=username)
LIVE_SITE_PASSWORD=$(terminus lock:info $TERMINUS_SITE.live --field=password)
```

I suppose for backward compatibility, DEV_SITE_URL and the others *might* need to be left as is.  if this were deemed necessary, additional separate environment variables should be set. Something like this? 

```
echo "export MULTIDEV_SITE_UNLOCKED_URL='https://$MULTIDEV_SITE_USER:MULTIDEV_SITE_PASSWORD@$TERMINUS_ENV-$TERMINUS_SITE.pantheonsite.io/'"
echo "export DEV_SITE_UNLOCKED_URL='https://$DEV_SITE_USER:DEV_SITE_PASSWORD@dev-$TERMINUS_SITE.pantheonsite.io/'"
echo "export TEST_SITE_UNLOCKED_URL='https://$TEST_SITE_USER:TEST_SITE_PASSWORD@test-$TERMINUS_SITE.pantheonsite.io/'"
echo "export LIVE_SITE_UNLOCKED_URL='https://$LIVE_SITE_USER:LIVE_SITE_PASSWORD@test-$TERMINUS_SITE.pantheonsite.io/'"
```

It probably makes sense to move all this into a subroutine for creating the variables to reduce the sheer amount of duplicate code, and so the environment variables are added/modified only when the Lock is enabled.

**Comment by greg-1-anderson** [comment]
Having the build tools scripts look up the basic auth credentials on the fly seems too complicated to me.

It seems more tenable to use a single well-known username and password for all environments. If you did this, then we could have the build scripts check for a single environment variable that you could set in the Circle admin interface.

I don't think that you need to worry about the "unlocked" URL. I expect that a URL containing a username and password should still work on a site that does not have http basic auth enabled.

I might go for a PR that used Terminus to look up the username and password, but that part of the script would have to be conditional on an environment variable, e.g. set DYNAMIC_BASIC_AUTH_LOOKUP=1 in CircleCI to look up the variables via Terminus.

**Comment by jameswilson** [comment]
> It seems more tenable to use a single well-known username and password for all environments.

I get where you're coming from. However these variables are exposed in your UI per environment. So an unwitting webmaster or dev team member could come and change or remove the security lock info on an environment, breaking their dev team's setup.  

> we could have the build scripts check for a single environment variable that you could set in the Circle admin interface.

As of today, the only piece that is "required" is the user/pass for the dev environment — which is currently hardcoded into the visual regression test comparison.  I was just overengineering the above for theoretical completeness sake.

If we're checking for one variable, lets say the locked dev environment username, would it be acceptable to also just go ahead an look for the dev environment password field as well?

**Comment by greg-1-anderson** [comment]
At the end of the day, these test scripts are just examples; you can alter them as you wish to suit your own purposes.

I don't want to add the lock environment checks to set-environment, but I'd accept a PR that allowed an environment variable or variables to be set in CircleCI to provide authentication credentials to be used in the SUT URL.

I'd accept a PR to facilitate populating those variables dynamically, e.g. set-environment could `source` a well-known file in your site's .circleci directory, if it existed.

**Comment by jameswilson** [comment]
So something like these four lines of code:

```
if [[ -n {$DYNAMIC_BASIC_AUTH_LOOKUP} ]]; then
  USER=$(terminus lock:info $TERMINUS_SITE.dev --field=username)
  PASSWORD=$(terminus lock:info $TERMINUS_SITE.dev --field=password)
  echo "export DEV_SITE_URL='https://$USER:$PASSWORD@dev-$TERMINUS_SITE.pantheonsite.io/'"
fi
```

**Comment by jameswilson** [comment]
Apologies. was writing this while you posted.   So something like this?

```
// Assumes variable PANTHEON_DEV_SITE_BASIC_AUTH is set to "username:password"
if [[ -n {$PANTHEON_DEV_SITE_BASIC_AUTH} ]]; then
  echo "export DEV_SITE_URL='https://$PANTHEON_DEV_SITE_BASIC_AUTH@dev-$TERMINUS_SITE.pantheonsite.io/'"
fi
```

Will need to check elsewhere to see if there is a better pattern to follow for the environment variable name.

**Comment by jameswilson** [comment]
The existing variable naming conventions are documented here:

https://github.com/pantheon-systems/example-drops-8-composer/blob/5073f9f439867d2e09112636a8a7c391f09af3e3/.circleci/config.yml#L13-L20

```
    # TERMINUS_SITE:  Name of the Pantheon site to run tests on, e.g. my_site
    # TERMINUS_TOKEN: The Pantheon machine token
    # GITHUB_TOKEN:   The GitHub personal access token
    # GIT_EMAIL:      The email address to use when making commits
    #
    # TEST_SITE_NAME: The name of the test site to provide when installing.
    # ADMIN_PASSWORD: The admin password to use when installing.
    # ADMIN_EMAIL:    The email address to give the admin when installing.
```

It's not entirely clear if the TEST_SITE_NAME implies any relationship to the actual test environment on Pantheon, but so if it does, I'm thinking the name should be `DEV_SITE_BASIC_AUTH`, and the PR to this repo would also need a companion PR to https://github.com/pantheon-systems/example-drops-8-composer with a line like:
```
    # DEV_SITE_BASIC_AUTH: The 'username:password' to use if your dev environment is locked via Pantheon UI.
```

**Comment by jameswilson** [comment]
> I'd accept a PR to facilitate populating those variables dynamically, e.g. set-environment could source a well-known file in your site's .circleci directory, if it existed.

I like this idea too, but it feels like this would be a common enough problem for folks to have an in-built way to handle this straight during their initial site setup, instead of having to figure out how to add an `.env` file with the appropriately named variables to override the `DEV_SITE_URL` environment variable.  Perhaps this could be filed as a follow-up issue though, it could be helpful for plenty other cases.

**Comment by jameswilson** [comment]
> It's not entirely clear if the TEST_SITE_NAME implies any relationship to the actual test environment on Pantheon,

Doh. Ignore this. If I understand correctly, I think this is the site_name variable used when installing Drupal from scratch — a totally separate matter. Though tbh, I'm not sure when a from-scratch install is done, as all our multidev environments created from PRs just clone the database from dev.

**Comment by greg-1-anderson** [comment]
Early versions of the Build Tools workflow did a site install at the beginning of each test, with the expectation that the agency would build fixtures to test their sites. In practice, it seems that almost everyone wants to just test from a database cloned from an actual instance of their site, so we moved away from this.

**Comment by greg-1-anderson** [comment]
I think the common case here is to have documentation that tells users what environment variable to set in CircleCI to specify their http basic auth credentials to use in testing.

**Comment by jameswilson** [comment]
@greg-1-anderson there you go.  two PRs for your consideration.

**Comment by jameswilson** [comment]
So I've run the CircleCI test suite on a PR branch that was failing, and the visual regression test console output does appear to be reporting URLs with the Basic Auth included (and even masked!) which is a good thing:

**Before:**
```
Pinging the pr-143 multidev environment to wake it from sleep...
Pinging the dev environment to wake it from sleep...
Running backstop reference on https://dev-*******.pantheonsite.io/...
BackstopJS v4.1.9
```

**After:**
```
Pinging the pr-143 multidev environment to wake it from sleep...
Pinging the dev environment to wake it from sleep...
Running backstop reference on https://*************@dev-*******.pantheonsite.io/...
BackstopJS v4.1.9
```

However, later on in the script, I'm still getting failures in the visual comparison steps:

```
   See: /root/example_drops_8_composer/backstop_data/bitmaps_test/20200716-195634/failed_diff_test_Hello_World_0_document_0_phone.png
      compare | ERROR { requireSameDimensions: false, size: isDifferent, content: 13.85%, threshold: 0.1% }: Hello World test_Hello_World_0_document_0_phone.png
   See: /root/example_drops_8_composer/backstop_data/bitmaps_test/20200716-195634/failed_diff_test_Homepage_0_document_0_phone.png
   See: /root/example_drops_8_composer/backstop_data/bitmaps_test/20200716-195634/failed_diff_test_Hello_World_0_document_1_tablet.png
      compare | ERROR { requireSameDimensions: false, size: isDifferent, content: 5.33%, threshold: 0.1% }: Homepage test_Homepage_0_document_0_phone.png
      compare | ERROR { requireSameDimensions: false, size: isDifferent, content: 28.93%, threshold: 0.1% }: Hello World test_Hello_World_0_document_1_tablet.png
   See: /root/example_drops_8_composer/backstop_data/bitmaps_test/20200716-195634/failed_diff_test_Hello_World_0_document_2_desktop.png
      compare | ERROR { requireSameDimensions: false, size: isDifferent, content: 41.06%, threshold: 0.1% }: Hello World test_Hello_World_0_document_2_desktop.png
   See: /root/example_drops_8_composer/backstop_data/bitmaps_test/20200716-195634/failed_diff_test_Homepage_0_document_1_tablet.png
      compare | ERROR { requireSameDimensions: false, size: isDifferent, content: 11.97%, threshold: 0.1% }: Homepage test_Homepage_0_document_1_tablet.png
   See: /root/example_drops_8_composer/backstop_data/bitmaps_test/20200716-195634/failed_diff_test_Homepage_0_document_2_desktop.png
      compare | ERROR { requireSameDimensions: false, size: isDifferent, content: 14.56%, threshold: 0.1% }: Homepage test_Homepage_0_document_2_desktop.png
       report | Test completed...
       report | 0 Passed
       report | 6 Failed
       report | Writing jUnit Report
       report | jUnit report written to: backstop_data/ci_report/xunit.xml
       report | Writing browser report
       report | Resources copied
       report | Copied json report to: /root/example_drops_8_composer/backstop_data/bitmaps_test/20200716-195634/report.json
       report | Copied jsonp report to: /root/example_drops_8_composer/backstop_data/html_report/config.js
      COMMAND | Executing core for "openReport"
   openReport | Attempting to ping 
   openReport | Remote not found. Opening backstop_data/html_report/index.html
       report | *** Mismatch errors found ***
      COMMAND | Command "report" ended with an error after [2.897s]
      COMMAND | Error: Mismatch errors found.
                    at /usr/local/lib/node_modules/backstopjs/core/command/report.js:189:17
                    at process._tickCallback (internal/process/next_tick.js:68:7)
      COMMAND | Command "test" ended with an error after [10.598s]
      COMMAND | Error: Mismatch errors found.
                    at /usr/local/lib/node_modules/backstopjs/core/command/report.js:189:17
                    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The screenshots uploaded to the CircleCI artifacts folder are still showing the lock screen for the dev environment:

Dev:
![test_Hello_World_0_document_0_phone](https://user-images.githubusercontent.com/243532/87747460-0978a480-c7b9-11ea-8bc6-2bf85409c19e.png)

Diff:
![failed_diff_test_Hello_World_0_document_0_phone](https://user-images.githubusercontent.com/243532/87747456-07aee100-c7b9-11ea-89e2-456bb6d80201.png)

super frustrating. I'm not sure what is going wrong.

**Comment by jameswilson** [comment]
Ah. I think I know what is going on.  We're using a vanity domain on the dev and test environments, and have added custom redirect logic in settings.php to forward from the pantheonsite.io urls to the vanity domain environments, more or less following the code snippet here https://pantheon.io/docs/redirects#redirect-with-php

In a web browser, when i access pantheonsite.io dev environment, I'm prompted for the HTTP Auth user/pass,  then the redirect happens, and then it asks for the HTTP Basic Auth again. I need to see if I can intercept the user/pass via PHP $_SERVER global variables, and pass it along in the redirect.

**Comment by jameswilson** [comment]
Okay. yes. that was the issue. And I've resolved it by forwarding the user/pass to the vanity domain ;with the following snippet:

```
/**
 * Redirect to primary domains on dev and test environments.
 * Note: the Primary Domain for the live environment is handled automatically
 * by Pantheon and can be adjusted in the Pantheon UI.
 */
if (isset($_ENV['PANTHEON_ENVIRONMENT']) && php_sapi_name() != 'cli') {

  if ($_ENV['PANTHEON_ENVIRONMENT'] === 'test') {
    $primary_domain = 'test.example.com';
  }
  elseif ($_ENV['PANTHEON_ENVIRONMENT'] === 'dev') {
    $primary_domain = 'dev.example.com';
  }
  else {
    // Redirect to HTTPS on every Pantheon environment.
    $primary_domain = $_SERVER['HTTP_HOST'];
  }

  $requires_redirect = FALSE;

  // Ensure the site is being served from the primary domain.
  if ($_SERVER['HTTP_HOST'] != $primary_domain) {
    $requires_redirect = TRUE;
  }

  // If you're not using HSTS in the pantheon.yml file, uncomment this next block.
  if (
    !isset($_SERVER['HTTP_USER_AGENT_HTTPS']) ||
    $_SERVER['HTTP_USER_AGENT_HTTPS'] != 'ON'
  ) {
    $requires_redirect = TRUE;
  }

  if ($requires_redirect === TRUE) {

    $basic_auth = '';
    if (!empty($_SERVER['PHP_AUTH_USER']) && !empty($_SERVER['PHP_AUTH_PW'])) {
      $basic_auth = urlencode($_SERVER['PHP_AUTH_USER']) . ':' . urlencode($_SERVER['PHP_AUTH_PW']) . '@';
    }

    // Name transaction "redirect" in New Relic for improved reporting (optional).
    if (extension_loaded('newrelic')) {
      newrelic_name_transaction("redirect");
    }

    header('HTTP/1.0 301 Moved Permanently');
    header('Location: https://'. $basic_auth . $primary_domain . $_SERVER['REQUEST_URI']);
    exit();
  }
  // Drupal 8 Trusted Host Settings
  if (is_array($settings)) {
    $settings['trusted_host_patterns'] = array('^'. preg_quote($primary_domain) .'$');
  }
}
```

I think this functionality is working as expected now.  Thanks for bearing with me.

**Comment by kporras07** [comment]
This seems to be solved now. Feel free to reopen if further discussion is needed :)
