### ISSUE TITLE
Circleci scheduled_update_check failing with sh: 1: set: Illegal option -o pipefail since last commit

### ISSUE THREAD

**Issue by sagannotcarl** [pantheon-systems/docker-build-tools-ci#64]
Starting with pull request #63 my circleci scheduled_update_check task has been failing with the error `sh: 1: set: Illegal option -o pipefail`. All passes before the image was updated and all fails since.

The timing seems to be related to #63 which brings in the changes from https://github.com/pantheon-systems/terminus-clu-plugin/pull/9.

As far as I gotten debugging it is that it's a sh/bash issue but I don't understand how the update to terminus-clu-plugin would impact this.

Here the circleci log for reference:

```
#!/bin/bash -eo pipefail
set -e && terminus project:clu $TERMINUS_SITE

 [notice] Rsync ***@***.drush.in:code/build-metadata.json => /tmp/build-metadata.json
 [notice] Executing git clone ***/*********** /tmp/local-sitecBRmCd
Cloning into '/tmp/local-sitecBRmCd'...
 [notice] 
 [notice] Call GitHub API: GET repos/***/***********/pulls?state=open
 [notice] Running composer install --working-dir=/tmp/local-sitecBRmCd --no-dev --no-interaction
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 147 installs, 0 updates, 0 removals
[...]
9 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Scaffolding files for drupal/core:
[...]
Scaffolding files for pantheon-systems/drupal-integrations:
  - Copy [project-root]/.drush-lock-update from assets/drush-lock-update
  - Copy [web-root]/sites/default/default.services.pantheon.preproduction.yml from assets/default.services.pantheon.preproduction.yml
  - Copy [web-root]/sites/default/settings.pantheon.php from assets/settings.pantheon.php
> DrupalProject\composer\ScriptHandler::createRequiredFiles
Create a sites/default/files directory with chmod 0777
 [notice] Running set -o pipefail && composer update --working-dir=/tmp/local-sitecBRmCd --no-progress --no-dev --no-interaction 2>&1 | tee /tmp/local-sitecBRmCd/vendor/update.log
sh: 1: set: Illegal option -o pipefail
 [error]  Command `set -o pipefail && composer update --working-dir=/tmp/local-sitecBRmCd --no-progress --no-dev --no-interaction 2>&1 | tee /tmp/local-sitecBRmCd/vendor/update.log` failed with exit code 2 

Exited with code exit status 1

CircleCI received exit code 1

```

**Comment by greg-1-anderson** [comment]
> [notice] Running set -o pipefail && composer update

Looks like clu might have added `set -o pipefail &&` before the `composer update` command, and this is perhaps incompatible with the shell we are using in our Docker container.

We could roll back to a working version of clu, or maybe try to use a different shell in our container.

**Comment by sagannotcarl** [comment]
clu is tracking this issue here: https://github.com/pantheon-systems/terminus-clu-plugin/issues/8

**Comment by aaronbauman** [comment]
I just merged https://github.com/pantheon-systems/terminus-clu-plugin/pull/10 which has resolved the issue for me.

Will tag a new release shortly

**Comment by davereid-pfg** [comment]
Ugh, I swear I had tested this in our CircleCI container, but not through the command. Thanks for the follow-up @aaronbauman.

**Comment by sagannotcarl** [comment]
Circleci scheduled_update_check working again! Thanks!
