### ISSUE TITLE
Switch to Composer 2

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/docker-build-tools-ci#66]
Composer 2 can run `composer install` significantly faster than Composer 1. Switching to Composer 2 in this container will greatly speed up build for projects using the container.

This switch probably warrants a major version bump.

**Comment by sagannotcarl** [comment]
I've started getting the following error when using composer:

```
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
```

I've been stalling on updating to composer 2 locally because my scheduled_update_check circleci job just reverts the lockfile to the composer 1 style.

**Comment by kporras07** [comment]
This was done in 7.x branch and pushed both to PHP 7.4 and 8.0 version images
