### ISSUE TITLE
Build tools create public GitHub repo

### ISSUE THREAD

**Issue by jraviotta** [pantheon-systems/docker-build-tools-ci#7]
This May be an issue with the build tools in general.

When executing a new build in the Docker container, a public GitHub repo is created. I would prefer that the visibility be set to private by default. I am more likely to use build tools for client sites that open source projects. Moreover, I usually have to debug the build multiple times before I would ever want to share with collaborators.

**Comment by greg-1-anderson** [comment]
This is a feature request for the Terminus Build Tools plugin
