### ISSUE TITLE
Create a version of the Build Tools utilizing PHP 7.4.

### ISSUE THREAD

**Issue by stovak** [pantheon-systems/docker-build-tools-ci#77]
Implementation of Pantheon Internal CMS-21.

**Comment by stovak** [comment]
requirements: 
- Integration with quay so it builds new images automatically
- Composer 2
- pcov module for PHP unit test coverage data without xdebug
- GitHub Actions CI template in the repo for people to add to their drupal installs (not sure how those templates work)

**Comment by stovak** [comment]
Here are my changes... use what you care to: https://github.com/stovak/docker-build-tools-ci

**Comment by kporras07** [comment]
Hi @stovak I started working on this. WIP at https://github.com/pantheon-systems/docker-build-tools-ci/compare/6.x...kporras07:7.4.x?expand=1 

Questions:
1) Should I create a new branch or PR against 6.x branch? If new, what name?
2) Quay.io: should I setup automatic build for all branches? This could be done directly in quay.io. I think I have the access level needed for this.

Please let me know how to continue with this :)

**Comment by stovak** [comment]
1. Yes create two new branches based on 6.x's latest commit, php 7.4 and 8.
2. only set up CI on the new branches for the moment. If we need to backport we will.

**Comment by kporras07** [comment]
Pushed as 7.x-php7.4
