### ISSUE TITLE
Create a version of the Build Tools utilizing PHP 8.0

### ISSUE THREAD

**Issue by stovak** [pantheon-systems/docker-build-tools-ci#78]
Implementation of Pantheon Internal CMS-21.

**Comment by stovak** [comment]
requirements: 
- Integration with quay so it builds new images automatically
- Composer 2
- pcov module for PHP unit test coverage data without xdebug
- GitHub Actions CI template in the repo for people to add to their drupal installs (not sure how those templates work)

**Comment by kporras07** [comment]
Pushed as 7.x-php8.0
